CREATE TABLE etl_data (
    SourceDocumentID TEXT,
    FileName TEXT,
    Title TEXT,
    QCScanDate DATE,
    CMODLoadDate DATE,
    ScanDate DATE,
    DocumentID TEXT,
    BatchReferenceID TEXT,
    BatchClassName TEXT,
    Source TEXT,
    AutoCorrect TEXT,
    ScanUserID TEXT,
    Category TEXT,
    SourceBatchID TEXT,
    SourceCreatedDate DATE,
    SourceCreator TEXT,
    SourceModifiedDate DATE,
    SourceModifier TEXT,
    String_Field_1 TEXT,
    String_Field_2 TEXT,
    String_Field_3 TEXT,
    Date_Field_1 DATE,
    lot_id TEXT
);
